### ISSUE TITLE
Getting nan ms/cm for output

### ISSUE THREAD

**Issue by akinich** [GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#1]
Thank you for sharing the library!

I'm using this on the arduino IDE on an esp32 dev board.
I had to make a few changes to the code, mainly change the gain from 1 to 2/3 to get the right voltage reading on the adc.
After getting the voltage and referencing it with a multi meter i am still unable to get the ec as its just giving nan.

**Comment by MkLHX** [comment]
Hi, can you give us more details about sketch and ESP board please?
as you can see here when using ADC ADS1115 you can choose your GAIN like this 
https://github.com/adafruit/Adafruit_ADS1X15/blob/master/examples/singleended/singleended.pde#L22
without sketch it's difficult to give help

**Comment by akinich** [comment]
instead of declaring the gain , I directly multiplied the value with the factor ( 0.1875 for 2/3) 
the ec sensor is on pin 0 of ads1115. at this moment the output voltage from the sensor using the multimeter and the output voltage from the adc are the same.

```

/*
 * file DFRobot_ESP_EC_BY_GREENPONIK.ino
 * @ https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK
 *
 * This is the sample code for Gravity: Analog EC Sensor / Meter Kit V2, SKU:DFR300
 *  * In order to guarantee precision, a temperature sensor such as DS18B20 is needed, to execute automatic temperature compensation.
 * You can send commands in the serial monitor to execute the calibration.
 * Serial Commands:
 *   enterec -> enter the calibration mode
 *   calec   -> calibrate with the standard buffer solution, two buffer solutions(1413us/cm and 12.88ms/cm) will be automaticlly recognized
 *   exitec  -> save the calibrated parameters and exit from calibration mode
 * 
 * Based on the @ https://github.com/DFRobot/DFRobot_EC
 * Copyright   [DFRobot](http://www.dfrobot.com), 2018
 * Copyright   GNU Lesser General Public License
 *
 * ##################################################
 * ##################################################
 * ########## Fork on github by GreenPonik ##########
 * ############# ONLY ESP COMPATIBLE ################
 * ##################################################
 * ##################################################
 * 
 * version  V1.1
 * date  2019-06
 */

#include "Arduino.h"
#include "Adafruit_ADS1015.h"
#include "DFRobot_ESP_EC.h"
#include "EEPROM.h"
#include "wire.h"
DFRobot_ESP_EC ec;
Adafruit_ADS1115 ads;

float voltage, ecValue, temperature = 25;

void setup()
{
	Serial.begin(115200);
  Wire.begin(21,22);
	EEPROM.begin(32);//needed EEPROM.begin to store calibration k in eeprom
	ec.begin();//by default lib store calibration k since 10 change it by set ec.begin(30); to start from 30
	//ads.setGain(GAIN_ONE);
	ads.begin();
}

void loop()
{
	static unsigned long timepoint = millis();
	if (millis() - timepoint > 1000U) //time interval: 1s
	{

		timepoint = millis();
		voltage = ads.readADC_SingleEnded(0) * 0.1875;
		Serial.print("voltage:");
		Serial.println(voltage, 4);

		//temperature = readTemperature();  // read your temperature sensor to execute temperature compensation
		Serial.print("temperature:");
		Serial.print(temperature, 1);
		Serial.println("^C");

		ecValue = ec.readEC(voltage, temperature); // convert voltage to EC with temperature compensation
		Serial.print("EC:");
		Serial.print(ecValue, 4);
		Serial.println("ms/cm");
	}
	ec.calibration(voltage, temperature); // calibration process by Serail CMD
}

float readTemperature()
{
	//add your code here to get the temperature from your temperature sensor
}
```

**Comment by MkLHX** [comment]
and when you try just run the example sketch without modifications it's work?

**Comment by akinich** [comment]
Nope, the example did not work , that's why i modified the code  a bit.

also im getting this error in the console 

> WARNING: library DFRobot_ESP_EC_BY_GREENPONIK-master claims to run on (espressif32) architecture(s) and may be incompatible with your current board which runs on (esp32) architecture(s).

**Comment by MkLHX** [comment]
ok i got it! the issue is not in the sketch or lib but I made an error in the library.properties architecture field try to download lib again on you computer, restart Arduino IDE and retry the example sketch.

**Comment by akinich** [comment]
Which library do you suggest i install? And does this work on arduino or only platformio?
I am currently using this code on arduino's ide

**Comment by MkLHX** [comment]
I suggest you to download the lastest GreenPonik EC_ESP lib an retry using example sketch. We use the lib both Arduino IDE & platformio

**Comment by akinich** [comment]
I am going to re-download [https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK](this library) and run the example code. The ads1115 will be connected to the esp32 via i2c and the EC sensor will be connected to the A0 on the ads1115.

**Comment by akinich** [comment]
I am going to re-download [this library](https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK) and run the example code. 
The ads1115 will be connected to the esp32 via i2c and the EC sensor will be connected to the A0 on the ads1115.

**Comment by akinich** [comment]
Hello again. I re-downloaded the library and ran the example code without any changes. 
There are a couple of issues I'd like to point out. 
First - running the example code without any changes still gives a "nan" for ec. 
Second - the output from the adc in terms of voltage is incorrect. I highly recommend making the changes for the adc code. I can explain it to you if you'd like. 

I've attached a screenshot of the serial monitor output for you to take a look.
The A0 pin is currently connected to the 3.3v pin but the voltage being displayed is 2.6v.
![Screenshot 2019-06-08 at 2 14 34 PM](https://user-images.githubusercontent.com/4410595/59144623-e4333780-89f7-11e9-9e9e-9351347a1a83.png)

**Comment by MkLHX** [comment]
Sorry but as you can see on this video we use it on ESP32 Dev Module board without any bug or problem.
https://youtu.be/EqFw561pO5k

So i don't know whats happen in your configuration but when we use it like on the video we run the lib well.

**Comment by mntolia** [comment]
Hi @MkLHX ,
I am working with @akinich and I figured out the issue. I replaced "readFloat()" and "writeFloat()" functions with "read()" and "write()" and it started working.

**Comment by MkLHX** [comment]
Hi! have you the latest version of EEPROM lib on your ide?
I opened Arduino IDE, select EEPROM WRITE example, open the sketch, add a line => EEPROM.readFloat(0); just above EEPROM.write(addr,val); and run ctrl+r the sketch is compiled without any error.

```
/*
   EEPROM Write

   Stores random values into the EEPROM.
   These values will stay in the EEPROM when the board is
   turned off and may be retrieved later by another sketch.
*/

#include "EEPROM.h"

// the current address in the EEPROM (i.e. which byte
// we're going to write to next)
int addr = 0;
#define EEPROM_SIZE 64
void setup()
{
  Serial.begin(115200);
  Serial.println("start...");
  if (!EEPROM.begin(EEPROM_SIZE))
  {
    Serial.println("failed to initialise EEPROM"); delay(1000000);
  }
  Serial.println(" bytes read from Flash . Values are:");
  for (int i = 0; i < EEPROM_SIZE; i++)
  {
    Serial.print(byte(EEPROM.read(i))); Serial.print(" ");
  }
  Serial.println();
  Serial.println("writing random n. in memory");
}

void loop()
{
  // need to divide by 4 because analog inputs range from
  // 0 to 1023 and each byte of the EEPROM can only hold a
  // value from 0 to 255.
  // int val = analogRead(10) / 4;
  int val = byte(random(10020));
  // write the value to the appropriate byte of the EEPROM.
  // these values will remain there when the board is
  // turned off.
 /*===>*/ EEPROM.readFloat(0); /*<===*/
  EEPROM.write(addr, val);
  Serial.print(val); Serial.print(" ");
  // advance to the next address.  there are 512 bytes in
  // the EEPROM, so go back to 0 when we hit 512.
  // save all changes to the flash.
  addr = addr + 1;
  if (addr == EEPROM_SIZE)
  {
    Serial.println();
    addr = 0;
    EEPROM.commit();
    Serial.print(EEPROM_SIZE);
    Serial.println(" bytes written on Flash . Values are:");
    for (int i = 0; i < EEPROM_SIZE; i++)
    {
      Serial.print(byte(EEPROM.read(i))); Serial.print(" ");
    }
    Serial.println(); Serial.println("----------------------------------");
  }

  delay(100);
}
``` 
So i don't know why you need change eeprom method.

**Comment by mntolia** [comment]
The program compiles fine but it shows "NaN" in the serial monitor when the readFloat() function is called.
It displays correctly when read() is called.

It doesn't show any updates for the EEPROM library.

**Comment by MkLHX** [comment]
Hi @akinich and @mntolia! wee find the problem and we make patch about this. Now the 1.1.4 release is ok with this trouble.
You can make somes test and give us feedback. bye
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK/releases/tag/1.1.4

**Comment by mntolia** [comment]
Thanks @MkLHX will try it out later.

We got it working it using the preferences library.
