### ISSUE TITLE
wrong ec value

### ISSUE THREAD

**Issue by sakirun** [GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#2]
Dear,
I just try use esp32 with tds sensor with original code,  and esp8266  (12e) with modified version show similar result.

this is when the probe not in the water:
21:02:27.054 -> voltage:265.0000
21:02:27.054 -> temperature:25.0^C
21:02:27.054 -> >>>rawEC: 1.6159, ecValue: 412.0427<<<
21:02:27.054 -> EC:412.0427ms/cm
21:02:28.065 -> voltage:265.0000
21:02:28.065 -> temperature:25.0^C
21:02:28.065 -> >>>rawEC: 1.6159, ecValue: 412.0427<<<
21:02:28.065 -> EC:412.0427ms/cm

this result when the probe in the nutrition water  (1226ppm or 2.45ms)

21:04:36.184 -> voltage:1878.0000
21:04:36.184 -> temperature:25.0^C
21:04:36.184 -> >>>rawEC: 11.4512, ecValue: 2920.0610<<<
21:04:36.184 -> EC:2920.0610ms/cm
21:04:37.196 -> voltage:1878.0000
21:04:37.196 -> temperature:25.0^C
21:04:37.196 -> >>>rawEC: 11.4512, ecValue: 2920.0610<<<
21:04:37.196 -> EC:2920.0610ms/cm

the voltage from analog read seem way too high

**Comment by MkLHX** [comment]
Hi @sakirun,

This lib does not work with ESP8266. And it's work only with the DFRobot kit DFR0300.
If you're not on this configuration i cannot help you to manage EC measurement.

Did you run calibration?

You can fork the lib and adapt the rawEc range on the header.
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK/blob/master/src/DFRobot_ESP_EC.h#L27

**Comment by Timjena** [comment]
Hello , 

I m  using an esp32 it works fine one day and now I can not calibrate while out of range is here everything crashes please help the voltage is also very hight and when the probe is outside solution it displays 0.243ms/cm .


14:42:47.894 -> voltage:104.0000
14:42:47.894 -> temperature:25.0^C
14:42:47.894 -> >>>rawEC: 0.6341, ecValue: 0.6341<<<
14:42:47.894 -> EC:0.6341ms/cm
14:42:48.895 -> voltage:104.0000
14:42:48.895 -> temperature:25.0^C
14:42:48.895 -> >>>rawEC: 0.6341, ecValue: 0.6341<<<
14:42:48.895 -> EC:0.6341ms/cm
14:42:49.895 -> voltage:104.0000
14:42:49.895 -> temperature:25.0^C
14:42:49.895 -> >>>rawEC: 0.6341, ecValue: 0.6341<<<
14:42:49.895 -> EC:0.6341ms/cm
14:42:50.895 -> voltage:104.0000
14:42:50.895 -> temperature:25.0^C
14:42:50.895 -> >>>rawEC: 0.6341, ecValue: 0.6341<<<
14:42:50.895 -> EC:0.6341ms/cm

**Comment by MkLHX** [comment]
@Timjena what measurement circuit are you using? Did you use an ADC to get better voltage value on the circuit?
https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK

If you haven't calibrate your probe it's could be normal you get a value when the probe is out of the solution.

**Comment by sakirun** [comment]
> Hi @sakirun,
> 
> This lib does not work with ESP8266. And it's work only with the DFRobot kit DFR0300.
> If you're not on this configuration i cannot help you to manage EC measurement.

Ok,  I understand. I use different type   of sensor and I manage to solve it by changing your code, I'll fork this project later

**Comment by MkLHX** [comment]
> 
> 
> > Hi @sakirun,
> > This lib does not work with ESP8266. And it's work only with the DFRobot kit DFR0300.
> > If you're not on this configuration i cannot help you to manage EC measurement.
> 
> Ok, I understand. I use different type of sensor and I manage to solve it by changing your code, I'll fork this project later

i'think you cannot get any success with different sensors because the DFRobot library use voltage ranges or rawEC to determine wich calibration solutions are used... We tried to do the best we can to make it compatible with every kind of configurations without any success. So we decided to keep configuration on ESP32 and DFrobot DFR0300 an nothing else.

**Comment by MkLHX** [comment]
Please check mandatory cases:
- https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#dfrobot_esp_ec_by_greenponik-library
- https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#compatibility

**Comment by Timjena** [comment]
Can Not Calibrate Please Help it is in solution 12.88 for now and shows 9.5 and can not be calibrated 




>>>Enter EC Calibration Mode<<<
>>>Please put the probe into the 1413us/cm or 2.76ms/cm or 12.88ms/cm buffer solution<<<
>>>Only need two point for calibration one low (1413us/com) and one high(2.76ms/cm or 12.88ms/cm)<<<

voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091>>>Buffer Solution Error Try Again<<<   
>>>KValueTemp calculation formule: RES2 * ECREF * compECsolution / 1000.0 / voltage<<<
>>>KValueTemp calculation: 820.00 * 200.00 * 1.36 / 1000.0 / 1225.00<<<

>>>KValueTemp: 0.18<<<

>>>KValueTemp out of range 0.5-2.0<<<
>>>KValueTemp: 0.1822<<<
>>>Failed,Try Again<<<

voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
>>>rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1227.0000

**Comment by joshcoward63** [comment]
I know this was closed a while ago but I'm having the exact same scenario occur but with fresh out of the box probe.
Works just fine for the 1413 solution but never works for the 12.88

**Comment by MkLHX** [comment]
Hello @joshcoward63 you get an answer on the other issue #4.
The reason is simple, no calibration no correct read.
