### ISSUE TITLE
Ec toTDS value

### ISSUE THREAD

**Issue by sajalbhargava** [GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#5]
Hi,
thanks for the code , i wanna ask how to convert the "ec" value to TDS ?
thanks in advance :)

**Comment by MkLHX** [comment]
Hi!
as you can see DFRobot sell diferents kits for [Conductivity](https://www.dfrobot.com/product-1123.html) and [TDS](https://www.dfrobot.com/product-1662.html).

maybe you can use something like this converter
https://www.translatorscafe.com/unit-converter/en-US/electric-conductivity/14-19/electrical%20conductivity%20unit-TDS,%20parts%20per%20million,%20640%20scale/

And please open issue only about code issue.
